name: .NET Core Desktop

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Build
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Echo tag
        run: echo The tag is ${{ github.event.inputs.tag }}
      - name: Clean
        run: dotnet clean $env:GITHUB_WORKSPACE\WkyFast.sln --configuration Release && dotnet nuget locals all --clear
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run:  dotnet publish -c Release -r win-x64
      - run: powershell curl https://github.com/aiqinxuancai/DotNetDllPathPatcherWPF/releases/download/v0.0.14/DotNetDllPathPatcherCMD.zip -o DotNetDllPathPatcherCMD.zip
      - run: powershell Expand-Archive -Path .\DotNetDllPathPatcherCMD.zip -DestinationPath .\DotNetDllPathPatcherCMD
      - run: powershell .\DotNetDllPathPatcherCMD\publish\DotNetDllPathPatcherCMD.exe $env:GITHUB_WORKSPACE\WkyFast\bin\Release\net6.0-windows\win-x64\publish\WkyFast.exe --MyLibraryShrink
      - name: Compress
        run: powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\WkyFast\bin\Release\net6.0-windows\win-x64\publish -DestinationPath .\WkyFast.zip
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "WkyFast.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
